[target.aarch64-linux-android]
linker = "/home/runner/work/pr/pr/build/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang"
rustflags = []

[env]
CC_aarch64-linux-android = "/home/runner/work/pr/pr/build/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang"
AR_aarch64-linux-android = "/home/runner/work/pr/pr/build/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
CFLAGS_aarch64-linux-android = "-target aarch64-linux-android28"
